[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/css/et-book/*/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/css/et-book/*/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-ttf"


[[headers]]
  for = "/css/*.css"
  [headers.values]
  Access-Control-Allow-Origin = "*"
